name: valores
description: imprimir valores
inputs:
  nombre:
    description: 'Nombre'
    required: true
  apellido:
    description: 'Apellido'
    required: true
  edad:
    description: 'Edad'
    required: true
outputs:
  multiplicacion:
    description: 'Multiplicacion edad'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'


