name: imprimir_variables
on:
  push:
    branches: ["develop", "main", "release"]

jobs:
  variables:
    runs-on: ubuntu-latest
    environment: ${{github.ref_name == 'develop' && 'dev' || github.ref_name == 'main' && 'prod' || github.ref_name == 'release' && 'qa'}}
    workflow_dispatch:

    steps:
      - name:  Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run t1workflow.py
        run: |
          python t1workflow.py ${{ vars.NOMBRE }} ${{ vars.APELLIDO }} ${{ vars.EDAD }}

      - name: Imprimir entorno
        run: |
          echo "Estoy en el entorno: ${{ vars.ENTORNO  }}"